### ISSUE TITLE
Streams not moved to save_directory

### ISSUE THREAD

**Issue by camjac251** [mtverlee/lars#16]
Are you experiencing this bug as well? I have a lot of streams added to config file and notice that in the log it shows
```
09-Apr-19 05:36:24 - INFO - Checking channel twitch for streams!
09-Apr-19 05:36:24 - DEBUG - Starting thread for channel twitch.
09-Apr-19 05:36:24 - INFO - Channel twitch is already recording.
```
even though the channel is only hosting another at the moment, not streaming. It also happens for the other streams as well that are offline and not hosting.

I think that might be why streams aren't moved to the recorded folder because after the streamlink process ends when the stream goes offline, it's never moved because the log shows it still being recorded and I guess live.

I also see files in my lars repo folder with the channel names from config.ini but they are empty.

**Comment by mtverlee** [comment]
I have noticed that bug as well, however I haven't had the time to troubleshoot it. I'll look into it, or if you figure it out, definitely shoot over a PR. The only other thing I can think of besides a logic error to cause that would b the process not exiting cleanly for some reason and the lock file still being present?

The empty files you see in the lars repo folder are a lock file of sorts. When lars starts recording a stream, an empty file with the channel name is written to the repo do that lars knows it's recording that stream already. Otherwise, you end up with the issue of infinite threads being generated to record the same stream and the machine crashes.

I'm thinking it might have something to do with those files but I'll have a look when I can and see if I can figure it out.

**Comment by camjac251** [comment]
I noticed that streams I started recording when the process ran still have their lock files in the lars folder even though the stream ended a day ago. I also see lock files for all streams in the folder as well even though some didn't go live at all.

**Comment by mtverlee** [comment]
This should be fixed as of [this](https://github.com/mtverlee/lars/commit/0cfcf5a5540f39f178f36104e3427bfdf32c07ea) commit, but let me know if you still continue to have issues.

I've updated the code to have separate functions for moving files, checking for streams, and recording streams to help keep things neater.

I'll mark this issue closed but I'll reopen it if I need to.

**Comment by camjac251** [comment]
Thank you very much for the quick fix. Just in time for twitchcon :)

I'll let you know if I experience any other issues out of the 45 users monitored.

**Comment by camjac251** [comment]
Are the lock files supposed to be removed when the stream is over? I ran the script on a couple of channels but the lock files, I think, were still there after the stream ended and when it started again, no streamlink process was spawned to record
